spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydb
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
spring101:
  name: uncley
  content: "content name is ${spring101.name} and age is ${spring101.age}"
---
spring:
  profiles: test
spring101:
  age: 20

---
spring:
  profiles: prod
spring101:
  age: 40